version: '3.8'

services:
  app:
    build:
      context: .
      args:
        PORT: '${SEGMENTATION_SERVICE_PORT}'
    ports:
      - '${SEGMENTATION_SERVICE_PORT}:${SEGMENTATION_SERVICE_PORT}'
    volumes:
      - '/:/host-rootfs'
      - ./../normal-images:/app/normal-images
      - ./../corrected-images:/app/corrected-images
      - ./../processed-images:/app/processed-images
    environment:
      - PYTHONUNBUFFERED=1
      - PROCESSED_IMAGES_DIR=${PROCESSED_IMAGES_DIR}
      - NORMAL_IMAGES_DIR=${NORMAL_IMAGES_DIR}
      - CORRECTED_IMAGES_DIR=${CORRECTED_IMAGES_DIR}
    command: >
      sh -c "sleep 5 &&
      poetry run gunicorn -k uvicorn.workers.UvicornWorker -w 1
      -t 300 -b 0.0.0.0:8000 src.api.main:app"
